name: atoms_state
description: Simple State Management for flutter
version: 0.0.2
homepage: https://github.com/pyrossh/atoms_state

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: